name: first_app
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter

  shared_preferences: ^2.3.1
  flutter_bloc: ^8.1.6
  flutter_svg: ^2.0.10+1
  json_annotation: ^4.9.0
  meta: ^1.12.0
  dio: ^5.5.0+1
  retrofit: ^4.1.0
  flutter_localizations:
    sdk: flutter
  intl: any

dev_dependencies:
  json_serializable: ^6.8.0
  retrofit_generator: ^8.2.0 
  build_runner: ^2.4.11
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true
  generate: true
assets:
  - assets/images/icon.svg
