name: first_app
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  hexcolor: ^3.0.1
  json_annotation: ^4.9.0
  cupertino_icons: ^1.0.6
  meta: ^1.12.0
  dio: ^5.5.0+1
  retrofit: ^4.1.0

dev_dependencies:
  json_serializable: ^6.8.0
  retrofit_generator: '>=7.0.0 <8.0.0' 
  build_runner: ^2.4.11
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true
assets:
  - assets/images/icon.svg
